apiVersion: v1
kind: Pod
metadata:
  name: pokedex-flask
  namespace: nerdearla
spec:
  containers:
  - name: pokedex
    image: zdenkoo98/pokedex-flask-nerdearla:2
    ports:
    - containerPort: 5000