apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-flask
  namespace: nerdearla
  labels:
    app: pokedex-flask
spec:
  replicas: 5
  selector:
    matchLabels:
      app: pokedex-flask
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: pokedex-flask
    spec:
      containers:
      - name: pokedex
        image: zdenkoo98/pokedex-flask-nerdearla:1
        ports:
        - containerPort: 5000